[20기 이승무 최준식] Users 앱 SignUpView 로직 구현
wecode-bootcamp-korea/20-2nd-tteokbokcom-backend pull request #3
Opened 2021-05-24 14:29 UTC by JunsikChoi

## 수정 사항 간략한 한줄 요약
- SignUp 로직 및 헬퍼 유틸 구현
		 
## 수정 사항들 자세한 내용
- Validator (이메일, 패스워드, 유저네임, 중복검사) 및  커스텀 예외 클래스 정의 (9d3b618)
- 회원가입 뷰 로직 구현 (85ce1eb)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-05-31 01:59 UTC, Kang-kyunghun requested changes

2021-05-31 01:59 UTC, Kang-kyunghun commented on users/tests.py
> +        self.case_signupview_post_invalid_data()
1. 굳이 케이스를 만들고 다시 그 케이스들을 실행시키는 test 함수를 만들어야 할까요? 
2. test는 상황 하나 하나가 독립적으로 실행 되어야 하는데, 현재는 독립적으로 실행 된다고 보여지지 않습니다.

2021-05-31 04:05 UTC, JunsikChoi commented on users/tests.py
> +        self.case_signupview_post_invalid_data()
그렇군요!! 독립적인 테스트 되도록 수정하고 다시 리베이스하였습니다 :)

2021-06-01 11:50 UTC, JunsikChoi commented
Signin View 머지 가정 하에 컨플릭트 해결 미리 해놓았습니다.

2021-06-02 01:09 UTC, Kang-kyunghun commented
LGTM~~!

2021-06-02 01:09 UTC, merged